# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "aaefa0569898a6b81d421f8b6340bdc0"
name = "custom-field"
application_url = "https://instrumental-simon-devil-sparc.trycloudflare.com"
embedded = true

[build]
automatically_update_urls_on_dev = true
dev_store_url = "brandon-dev-marketplace.myshopify.com"
include_config_on_deploy = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products"

[auth]
redirect_urls = [
  "https://instrumental-simon-devil-sparc.trycloudflare.com/auth/callback",
  "https://instrumental-simon-devil-sparc.trycloudflare.com/auth/shopify/callback",
  "https://instrumental-simon-devil-sparc.trycloudflare.com/api/auth/callback"
]

[webhooks]
api_version = "2024-01"

[pos]
embedded = false
